FROM node:20-alpine AS builder

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install turbo
RUN npm install -g turbo

# Copy all files
COPY . .

# Prune to just the cleanup worker and its dependencies
RUN turbo prune @thronova/worker-cleanup --docker

# Add lockfile and package.json's of isolated subworkspace
FROM node:20-alpine AS installer
RUN apk add --no-cache libc6-compat
WORKDIR /app

# First install dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package-lock.json ./package-lock.json

RUN npm ci

# Build the project and its dependencies
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json

# Ensure prisma client is generated for dependencies
RUN npx prisma generate --schema=packages/database/prisma/schema.prisma

RUN npm run build --filter=@thronova/worker-cleanup...

FROM node:20-alpine AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 thronova

COPY --from=installer --chown=thronova:nodejs /app .

USER thronova

WORKDIR /app/apps/workers/cleanup
CMD ["npm", "start"]
